merlyn/assets/api/urls.py
# _*_ coding:utf-8 _*_
# __auth__: LJ

from django.conf import urls
from .views import (
    UserProfileListAPIView
)

urlpatterns = [

]

merlyn/assets/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views


urlpatterns = [
    url(r'^report_asset/$', views.report_asset),
    url(r'asset_list/$', views.display_asset_list, name='asset_list'),
    url(r'asset_list/(\d+)/$', views.display_asset_detail, name='asset_detail'),
    url(r'asset_list/list/$', views.fetch_asset_list, name='fetch_asset_list'),
    url(r'asset_list/category/(\d+)/$', views.fetch_asset_detail, name='fetch_asset_detail'),
    url(r'asset_list/category/$', views.fetch_asset_category, name='asset_category'),
    url(r'asset_event_logs/(\d+)/$', views.fetch_asset_event_logs, name='asset_event_logs'),
    url(r'^new_asset/approval/$', views.approval_new_asset),

]

merlyn/merlyn/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='dashboard'),
    url(r'^assets/', include('assets.urls', namespace='assets')),
    url(r'login/$',views.login, name='login'),
    url(r'logout/$',views.logout, name='logout'),
    url(r'^api/accounts', include('accounts.api.urls', namespace='accounts-api'))
]

merlyn/assets/models.py
# _*_ coding:utf-8 _*_

import sys
reload(sys)
sys.setdefaultencoding("utf-8")

from django.db import models
from accounts.models import UserProfile

# Create your models here.


class Manufactory(models.Model):
    # 硬件制造厂家
    name = models.CharField(u'厂商名称', max_length=64, unique=True)
    support_num = models.CharField(u'服务电话', max_length=30, blank=True, null=True)
    memo = models.TextField(u'备注信息', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'厂商'
        verbose_name_plural = u'厂商'


class BusinessUnit(models.Model):
    parent_unit = models.ForeignKey('self', related_name='parent_level', blank=True, null=True)
    name = models.CharField(u'业务线', max_length=64, unique=True)
    memo = models.TextField(u'备注', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'业务线'
        verbose_name_plural = u'业务线'


class Contract(models.Model):
    contract_no = models.CharField(u'合同号', max_length=128, unique=True)
    name = models.CharField(u'合同名称', max_length=128)
    memo = models.CharField(u'备注', max_length=128, blank=True, null=True)
    price = models.IntegerField(u'合同金额')
    detail = models.TextField(u'合同详细', blank=True, null=True)
    start_date = models.DateField(u'合同开始时间', blank=True)
    end_date = models.DateField(u'合同结束时间', blank=True)
    license_num = models.IntegerField(u'license数量', blank=True)
    create_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    class Meta:
        verbose_name = u'合同'
        verbose_name_plural = u'合同'

    def __str__(self):
        return self.name


class IDC(models.Model):
    name = models.CharField(u'机房名称', max_length=64, blank=True)
    memo = models.CharField(u'备注', max_length=128, blank=True, null=True)

    class Meta:
        verbose_name = u'机房'
        verbose_name_plural = u'机房'

    def __str__(self):
        return self.name


class AssetTag(models.Model):
    name = models.CharField(u'资产标签名称', max_length=64, unique=True)
    creator = models.ForeignKey(UserProfile)
    create_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'资产标签'
        verbose_name_plural = u'资产标签'


class EventLog(models.Model):
    name = models.CharField(u'事件名称', max_length=128)
    event_type_choices = (
        (1, u'硬件变更'),
        (2, u'新增配件'),
        (3, u'设备上线'),
        (4, u'设备下线'),
        (5, u'定期维护'),
        (6, u'业务上线\更新\变更'),
        (7, u'其它')
    )
    event_type = models.SmallIntegerField(u'事件类型', choices=event_type_choices)
    asset = models.ForeignKey('AssetCommonInfo')
    component = models.CharField(u'事件子项', max_length=255, null=True, blank=True)
    detail = models.TextField(u'事件详情')
    create_date = models.DateTimeField(u'事件创建时间', auto_now_add=True)
    user = models.ForeignKey(UserProfile, verbose_name=u'事件源')
    memo = models.CharField(u'备注', null=True, blank=True, max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'事件'
        verbose_name_plural = u'事件'


class Software(models.Model):
    # 操作系统,软件,固件版本相关
    type_choices = (
        ('linux', 'Linux'),
        ('windows', 'Windows'),
        ('network_firmware', 'Network Firmware'),
        ('software', 'Software')
    )
    os_distribution_choices = (
        ('windows', 'Windows'),
        ('centos', 'Centos'),
        ('ubuntu', 'Ubuntu')
    )
    language_choices = (
        ('cn', u'中文'),
        ('en', u'英文')
    )
    type = models.CharField(u'软件类型', max_length=64, choices=type_choices, help_text=u'eg.GNU/Linux', default=1)
    distribution = models.CharField(u'发行版本', max_length=32, choices=os_distribution_choices, default='windows')
    version = models.CharField(u'软件/系统版本', max_length=32, unique=True)
    language = models.CharField(u'软件/系统语言', max_length=32, default='cn', choices=language_choices)

    def __str__(self):
        return self.version

    class Meta:
        verbose_name = u'软件/系统'
        verbose_name_plural = u'软件/系统'


class AssetCommonInfo(models.Model):
    # 资产通用的信息
    asset_type_choices = (
        ('server', u'服务器'),
        ('switch', u'交换机'),
        ('router', u'路由器'),
        ('firewall', u'防火墙'),
        ('wireless', u'无线设备'),
        ('storage', u'存储设备'),
        ('software', u'软件资产'),
        ('other', u'其它资产')
    )

    asset_type = models.CharField(max_length=64, choices=asset_type_choices, default='server')
    name = models.CharField(max_length=64, unique=True)
    model = models.CharField(u'型号', max_length=128, null=True, blank=True)
    sn = models.CharField(u'资产SN号', max_length=128, unique=True)
    manufatory = models.ForeignKey('Manufactory', verbose_name=u'制造厂商')
    management_ip = models.GenericIPAddressField(u'管理IP', null=True, blank=True)
    contract = models.ForeignKey('Contract', verbose_name=u'合同', null=True, blank=True)
    purchase_date = models.DateField(u'购买时间', null=True, blank=True)
    expired_date = models.DateField(u'过保时间', null=True, blank=True)
    price = models.IntegerField(u'购买价格', null=True, blank=True)
    business_unit = models.ForeignKey('BusinessUnit', verbose_name=u'所属业务线', null=True, blank=True)
    admin = models.ForeignKey(UserProfile, verbose_name=u'资产管理员', null=True, blank=True)
    idc = models.ForeignKey('IDC', verbose_name=u'所属机房', null=True, blank=True)
    tags = models.ManyToManyField('AssetTag', blank=True)
    memo = models.TextField(u'备注', null=True, blank=True)
    create_date = models.DateTimeField(u'创建时间', blank=True, auto_now_add=True)
    update_date = models.DateTimeField(u'更新时间', blank=True, auto_now=True)

    class Meta:
        verbose_name = u'资产通用信息'
        verbose_name_plural = u'资产通用信息'

    def __str__(self):
        return self.name


class ServerAsset(models.Model):
    asset_common_info = models.OneToOneField('AssetCommonInfo')
    created_by_choices = (
        ('auto', 'Auto'),
        ('manual', 'Manual')
    )
    created_by = models.CharField(max_length=32, choices=created_by_choices, default='auto')
    hosted_on = models.ForeignKey('self', null=True, blank=True, related_name='hosted_on_server')
    raid_type = models.CharField(u'raid类型', null=True, blank=True, max_length=128)
    os_info = models.ForeignKey('Software')
    # os_type = models.CharField(u'操作系统类型', null=True, blank=True, max_length=64)
    # os_distribution = models.CharField(u'发行版本号', max_length=64, null=True, blank=True)
    # os_release = models.CharField(u'操作系统版本', max_length=64, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True, blank=True)
    update_date = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name = u'服务器'
        verbose_name_plural = u'服务器'

    def __str__(self):
        return self.asset_common_info.name


class NetworkDeviceAsset(models.Model):
    asset_common_info = models.OneToOneField('AssetCommonInfo')
    firmware = models.ForeignKey('Software')
    port_num = models.SmallIntegerField(u'端口数量', null=True, blank=True)
    device_detail = models.TextField(u'设备详情', null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True, blank=True)
    update_date = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name = u'网络设备'
        verbose_name_plural = u'网络设备'


class Component(models.Model):
    # common_asset_info = models.ForeignKey('AssetCommonInfo')
    name = models.CharField(u'名称', max_length=64, blank=True, null=True)
    manufatory = models.ForeignKey(u'Manufactory', null=True, blank=True)
    model = models.CharField(u'型号', max_length=128, blank=True)
    sn = models.CharField(u'SN号', max_length=128, null=True, blank=True)
    slot = models.CharField(u'插槽号', max_length=64, null=True, blank=True)
    memo = models.TextField(u'备注', null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name = u'组件的通用信息'
        verbose_name_plural = u'组件的通用信息'

    def __str__(self):
        return self.model


class CPU(Component):
    asset_common_info = models.ForeignKey('AssetCommonInfo')
    #component_common_info = models.OneToOneField('Component')
    # cpu_model = models.CharField(u'CPU型号', max_length=128, blank=True)
    #cpu_count = models.SmallIntegerField(u'CPU物理个数')
    cpu_core_count = models.SmallIntegerField(u'CPU核个数')
    frequency = models.CharField(u'主频', max_length=32, null=True, blank=True)
    # memo = models.TextField(u'备注', blank=True, null=True)
    # create_date = models.DateTimeField(auto_now_add=True)
    # update_date = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        verbose_name = u'CPU部件'
        verbose_name_plural = u'CPU部件'

    def __str__(self):
        return self.model


class RAM(Component):
    asset_common_info = models.ForeignKey('AssetCommonInfo')
    # sn = models.CharField(u'SN号', max_length=128, null=True, blank=True)
    # model = models.CharField(u'内存型号', max_length=128)
    # component_common_info = models.OneToOneField('Component')
    # slot = models.CharField(u'插槽号', max_length=64)
    capacity = models.IntegerField(u'内存大小(Mb)')
    # memo = models.CharField(u'备注', max_length=128, null=True, blank=True)
    # create_date = models.DateTimeField(auto_now_add=True, blank=True)
    # update_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return '%s:%s:%s' %(self.asset_common_info.id, self.slot, self.capacity)

    class Meta:
        verbose_name = 'RAM'
        verbose_name_plural = 'RAM'
        # unique_together = ('common_asset_info', 'slot')
    auto_create_fields = ['sn', 'slot', 'model', 'capacity']


class Disk(Component):
    asset_common_info = models.ForeignKey('AssetCommonInfo')
    # component_common_info = models.OneToOneField('Component')

merlyn/assets/api/views.py
# _*_ coding:utf-8 _*_
# __auth__: LJ

from rest_framework.generics import (
    ListAPIView
)

from  .serializers import (
    UserProfileSerializer
)

from ..customauth import (
    UserProfile
)


class UserProfileListAPIView(ListAPIView):
    serializer_class = UserProfileSerializer
    queryset = UserProfile.objects.all()

merlyn/assets/views.py
# coding: utf-8

from django.shortcuts import render
from django.http import HttpResponse
from core import AssetHandler
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
import json
import models
import data_format_handler
import utlis

# Create your views here.
def report_asset(request):
    # 资产数据汇报
    asset_handler = AssetHandler(request)
    if asset_handler.data_is_valid(): # 汇报的资产数据有效
        asset_handler.save_to_approval_zone_or_update_asset() # 插入资产数据到DB

    return HttpResponse(json.dumps(asset_handler.response.get_msg()))


@login_required
def approval_new_asset(request):
    # 批准新资产入库
    if request.method == 'POST':
        request.POST = request.POST.copy()
        approved_asset_id_list = request.POST.getlist('approved_asset_list')
        approved_asset_list = models.NewAssetApprovalZone.objects.filter(id__in=approved_asset_id_list)

        response_dict = {}
        for obj in approved_asset_list:
            request.POST['asset_data'] = obj.data
            asset_handler = AssetHandler(request)
            if asset_handler.data_is_valid():
                obj.approved = True
                obj.approved_by = request.user
                obj.save()
            asset_handler.save_approved_aseet(obj) # 保存已批准的通用资产信息
            response_dict[obj.id] = asset_handler.response.get_msg()

        return render(request, 'assets/new_assets_approval.html', {'new_assets': approved_asset_list, 'response_dict': response_dict})

    elif request.method == 'GET':
        ids = request.GET.get('ids')
        id_list = ids.split(',')
        new_asset_list = models.NewAssetApprovalZone.objects.filter(id__in=id_list)
        return render(request, 'assets/new_assets_approval.html', {'new_assets': new_asset_list})


@login_required
def display_asset_list(request):
    # 返回资产列表
    print 'display_asset_list'
    return render(request, 'assets/assets.html')


@login_required
def fetch_asset_list(request):
    # 返回格式化的资产数据
    print 'fetch_asset_list'
    asset_dict = data_format_handler.fetch_asset_list()
    print asset_dict
    return HttpResponse(json.dumps(asset_dict, default=utlis.json_date_handler))


@login_required
def asset_category(request):
    # 获取资产数据
    category_type = request.GET.get('category_type')
    if not category_type: category_type = 'server'
    if request.is_ajax():
        pass


@login_required
def display_asset_detail(request, asset_id):
    # 根据资产的ID获取资产信息并展示
    if request.method == 'GET':
        try:
            asset_obj = models.AssetCommonInfo.objects.get(id=asset_id)
        except ObjectDoesNotExist, e:
            return render(request, 'assets/asset_detail.html', {'error': e})

        return render(request, 'assets/asset_detail.html', {'asset_obj': asset_obj})


@login_required
def fetch_asset_detail(request, asset_id):
    # 根据资产的ID获取资产信息
    if request.method == 'GET':
        try:
            asset_obj = models.AssetCommonInfo.objects.get(id=asset_id)
        except ObjectDoesNotExist, e:
            return render(request, 'assets/asset_category.html', {'error': e})

        return render(request, 'assets/asset_category.html', {'asset_obj': asset_obj})


@login_required
def fetch_asset_event_logs(request, asset_id):
    # 获取事件日志记录
    print 'fetch_asset_event_logs'
    print asset_id
    if request.method == 'GET':
        log_list = data_format_handler.fetch_asset_event_logs(asset_id)
        return HttpResponse(json.dumps(log_list, default=utlis.json_datetime_handler))


@login_required
def fetch_asset_category(request):
    # 获取类别数据，展示类别数据
    category_type = request.GET.get('category_type')
    if not category_type:
        category_type = 'server'

    if request.is_ajax():
        category = data_format_handler.AssetCategory(request)
        data = category.serializer_data()
        return HttpResponse(data)
    else:
        return render(request, 'assets/asset_category.html', {'category_type': category_type})

merlyn/templates/assets/assets.html
{% extends 'base.html' %}

{% block header-css %}
<link rel="stylesheet" type="text/css" href="/static/plugins/DataTables/datatables.min.css"/>
{% endblock %}

{% block page-content-title %}
资产列表
{% endblock %}

{% block page-nav-tab %}
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li class="active">资产列表</li>
</ol>
{% endblock %}



{% block page-content %}
asset list
<div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">所有资产</h3>
        </div>
        <div class="panel-body" >
            <table id="asset_list" class="display table  table-hover">
              <thead >
                    <tr class="btn-info">
                        <th>资产ID</th>
                        <th>资产类型</th>
                        <th>Name</th>
                        <th>SN</th>

                        <th>IDC</th>
                        <th>业务线</th>
                        <th>管理IP</th>
                        <th>制造商</th>
                        <th>型号</th>
                        <th>CPU型号</th>
                        <th>CPU核数</th>
                        <th>内存(GB)</th>
                        <th>硬盘(GB)</th>
                        <th>状态</th>
                    </tr>
                </thead>
                <footer></footer>
            </table>


        </div>
    </div>


{% endblock %}



{% block bottom-js %}
<script type="text/javascript" src="/static/plugins/DataTables/datatables.min.js"></script>
<script type="text/javascript">
$(document).ready( function () {
    $("#container").removeClass("mainnav-lg");
    var table = $('#asset_list').DataTable( {
        initComplete: function () {
            this.api().columns().every( function () {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo( $(column.footer()).empty() )
                    .on( 'change', function () {
                        var val = $.fn.dataTable.util.escapeRegex(
                            $(this).val()
                        );
                        column
                            .search( val ? '^'+val+'$' : '', true, false )
                            .draw();
                    } );
                column.data().unique().sort().each( function ( d, j ) {
                    select.append( '<option value="'+d+'">'+d+'</option>' )
                } );
            } );
        },
        "ajax": "{% url 'assets:fetch_asset_list' %}",
        "scrollX": true,
        "pagingType": "full_numbers",
         "stateSave": true,
        "columns": [
            { "data": "id" },
            { "data": "asset_type" },
            { "data": "name" },
            { "data": "sn" },
            { "data": "idc" },
            { "data": "business_unit" },
            { "data": "management_ip" },
            { "data": "manufatory" },
            { "data": "model" },
            { "data": "cpu_model" },
            { "data": "cpu_core_count" },
            { "data": "ram_size" },
            { "data": "disk_size" },
            { "data": "status" },
        ],
      "columnDefs": [
        {
          targets: 0 ,//targets last column, use 0 for first column
          className: 'btn-link pointer',
         "data": "download_link",
         "render": function ( data, type, full, meta ) {
          return '<a class="btn-link" href="'+data+'" target="_blank">'+ data +'</a>';
          }
        }
      ]
    } ); //end datatables
    $('#asset_list td:first-child').addClass("btn-info");
    $('#asset_list').on('click', 'td:first-child', function () {
        console.log($(this).text());
    } );
} );//end doc ready
</script>
{% endblock %}

merlyn/templates/assets/new_assets_approval.html
{% extends 'base.html' %}
{% load asset_tags%}
{% block page-container %}
<div class="eq-height">

    <div class="col-sm-4 eq-box-sm">

        <!--Panel with Header-->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title" style="color: red;  ">确认要将下列资产存入数据库么？</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="">{% csrf_token %}
                <table class="table table-hover">
                    <tr>
                        <th>#</th>
                        <th>SN</th>
                        <th>资产类型</th>
                        <th>厂商</th>
                        <th>型号</th>
                        <th>CPU型号</th>
                        <th>CPU颗数</th>
                        <th>CPU核数</th>
                        <th>内存大小</th>
                        <th>汇报日期</th>

                    </tr>
                    {% for new_asset in new_assets %}
                    <tr data-set="{{ new_asset.id }}">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ new_asset.sn }}</td>
                        <td>{{ new_asset.asset_type }}</td>
                        <td>{{ new_asset.manufatory }}</td>
                        <td>{{ new_asset.model }}</td>
                        <td>{{ new_asset.data | get_cpu_model }}</td>
                        <td>{{ new_asset.data | get_cpu_count}}</td>
                        <td>{{ new_asset.data | get_cpu_core_count}}</td>
                        <td>{{ new_asset.ram_size}}</td>
                        <td>{{ new_asset.approved_date }}</td>
                            {{ response_dict}}
                            {% if new_asset.id  in response_dict %}
                                <td><a href="#">执行结果</a></td>
                            {% endif %}

                    </tr>
                    {% endfor %}



                </table>
                <select name="approved_asset_list"    class="hide" multiple>
                    {% for new_asset in new_assets %}
                    <option value="{{ new_asset.id }}" selected>{{ new_asset.sn }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Yes, I'm sure" class="btn btn-danger">

                </form>


                <div >
                    {% for key,msg in response_dic.items %}
                    <div>
                        {% for asset in new_assets %}
                            {% if asset.id == key %}
                                <h4 id="asset_{{ asset.id }}"><a style="color:deepskyblue" href="/admin/assets/asset/?q={{ asset.sn }}" target="_blank">{{ asset.sn }} </a> | {{ asset.manufactory }}  {{ asset.model }} | {{ asset.cpu_model }} </h4>
                            {% endif %}
                        {% endfor %}
                        <p style="color: green">
                            {% for item in msg.info %}
                                {{ item |safe}}
                                <br/>
                            {% endfor %}
                        </p>
                        <p style="color: red">
                            {% for item in msg.error %}

                                {% if 'Warning' in item.keys.0 %}
                                    <span style="color:orange;">{{ item }}</span>
                                {% else %}
                                    {{ item }}
                                {% endif %}
                                <br/>
                            {% endfor %}
                        </p>
                    </div>
                    <hr/>
                    {% endfor %}
                </div>

            </div>

        </div>
        <!--===================================================-->
        <!--End Panel with Header-->
<button id="scroll-top" class="btn"><i class="fa fa-chevron-up"></i></button>

    </div>


</div>

{% endblock %}